# Generated by Django 5.1 on 2026-06-26 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('lifetime_points', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze Brewer'), ('silver', 'Silver Ritualist'), ('gold', 'Gold Alchemist'), ('platinum', 'Platinum Maestro')], default='bronze', max_length=20)),
                ('stamps', models.PositiveIntegerField(default=0, help_text='Stamps toward next free drink')),
                ('total_stamps_earned', models.PositiveIntegerField(default=0)),
                ('free_drinks_available', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn_order', 'Points Earned from Order'), ('earn_stamp', 'Stamp Earned'), ('redeem_drink', 'Free Drink Redeemed'), ('redeem_points', 'Points Redeemed'), ('tier_bonus', 'Tier Bonus'), ('welcome', 'Welcome Bonus')], max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('stamps', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('order_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
